modLoader="javafml"
loaderVersion="[34,)"
license="GPL3"

[[mods]]
modId="configured"
version="0.2.0-1.16.3"
displayName="Configured"
credits=""
authors="MrCrayfish"
description="Creates a simple GUI config for every mod!"

[[dependencies.configured]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.configured]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
