modLoader="javafml"
loaderVersion="[34,)"
license="GPL3"

[[mods]]
modId="configured"
version="1.0.1"
displayName="Configured"
credits="Hatsondogs for creating icons. LizterZapZap for creating mod logo"
authors="MrCrayfish"
description="Creates a simple GUI config for every mod!"
logoFile="configured_logo.png"
logoBlur=false

[[dependencies.configured]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.configured]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.configured]]
    modId="configured"
    mandatory=false
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.configured]]
    modId="catalogue"
    mandatory=false
    versionRange="[1.2.0,)"
    ordering="NONE"
    side="CLIENT"

[modproperties.configured]
    catalogueImageIcon="configured_icon.png"
    configuredBackground="minecraft:textures/block/stone.png"
